import { motion } from 'motion/react';
import { TimelineData } from '../types';
import { VERDICT_COLORS } from '../constants';
import { X } from 'lucide-react';

interface ShareModalProps {
  scenario: string;
  data: TimelineData;
  onClose: () => void;
}

export default function ShareModal({ scenario, data, onClose }: ShareModalProps) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="relative w-full max-w-md bg-[#08090f] border border-white/20 rounded-2xl overflow-hidden shadow-2xl"
      >
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-white/50 hover:text-white z-10"
        >
          <X size={20} />
        </button>

        <div className="p-8" id="share-card">
          <div className="text-center mb-8">
            <h2 className="text-xs font-bold tracking-widest text-amber-400 uppercase mb-2">Brief History</h2>
            <h3 className="font-serif text-2xl text-white leading-tight">"{scenario}"</h3>
          </div>

          <div className="space-y-4 mb-8 relative">
            <div className="absolute left-[11px] top-2 bottom-2 w-0.5 bg-white/10"></div>
            {data.eras.map((era, i) => (
              <div key={i} className="flex items-start gap-4 relative z-10">
                <div className={`w-6 h-6 rounded-full flex-shrink-0 mt-0.5 border-2 border-[#08090f] ${VERDICT_COLORS[era.verdict]?.split(' ')[0] || 'bg-gray-600'}`}></div>
                <div>
                  <div className="text-sm font-bold text-white/90">{era.name}</div>
                  <div className="text-xs text-white/50">{era.verdict}</div>
                </div>
              </div>
            ))}
          </div>

          <div className="bg-white/5 rounded-xl p-4 border border-white/10">
            <p className="text-xs text-white/70 italic leading-relaxed">
              {data.evolutionSummary}
            </p>
          </div>
          
          <div className="mt-6 text-center text-[10px] text-white/30 uppercase tracking-widest">
            Generated by Legal Time Travel
          </div>
        </div>

        <div className="p-4 bg-white/5 border-t border-white/10 text-center">
          <p className="text-sm text-white/70">Take a screenshot to share!</p>
        </div>
      </motion.div>
    </div>
  );
}
